version: '3.8'

services:
  php-app:
    read_only: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/vendor
      - ./templates_c:/app/templates_c:rw

  tunnel:
    container_name: cloudflared-tunnel
    image: docker.io/cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=

networks:
  default:
